# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
matrix:
  include:
    - os: linux
      julia: 0.7
    - os: linux
      julia: 1.0
    - os: linux
      julia: nightly
    - os: linux
      julia: 1.0
      env: "CMAKEWRAPPER_JL_BUILD_FROM_SOURCE=1"
    - os: linux
      julia: nightly
      env: "CMAKEWRAPPER_JL_BUILD_FROM_SOURCE=1"
    - os: osx
      julia: 1.0
    - os: osx
      julia: 1.0
      env: "CMAKEWRAPPER_JL_BUILD_FROM_SOURCE=1"
notifications:
  email: false
branches:
  only: master
after_success:
  # push coverage results to Codecov
  - julia -e 'using Pkg; import CMake; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
