name: CI
on:
  - push
  - pull_request
jobs:
  Test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - From Source=${{ matrix.build_from_source }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.0'
          - '1.4'
          - 'nightly'
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
        arch:
          - x64
        build_from_source:
          - 0
          - 1
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/julia-buildpkg@latest
        env:
          CMAKEWRAPPER_JL_BUILD_FROM_SOURCE: ${{ matrix.build_from_source }}
      - uses: julia-actions/julia-runtest@latest
      - uses: julia-actions/julia-uploadcodecov@latest
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
